# Generated by Django 4.2.16 on 2024-10-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplate', '0001_original'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
