# Generated by Django 4.2.16 on 2024-10-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneplate', '0002_rename_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
    ]
