# Generated by Django 4.2.16 on 2024-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneplate', '0004_add_review_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, upload_to='ai_pics'),
        ),
    ]
